# Problem: You are given two strings s and t. t is generated by random shuffling string s and then add one more letter at a random position. Find the letter that was added in t.
def findTheDifference(s: str, t: str) -> str:
    """
    Approach: XOR.
    Time: O(N)
    Space: O(1)
    """
    res = 0
    for c in s + t:
        res ^= ord(c)
    return chr(res)
